[env]
TERM = "xterm-256color"

[font]
size = 10 

normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

[window]
padding.x = 14
padding.y = 14
decorations = "none"
opacity = 0.98

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500

