general.import = [
    "~/.config/alacritty/os_specific.toml"
]

[env]
TERM = "xterm-256color"

[font]
offset.x = 0
offset.y = 1
glyph_offset.x = 0
glyph_offset.y = 0

[window]
padding.x = 14
padding.y = 14
decorations = "none"
opacity = 0.98

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500

