[font]
size = 16 

normal = { family = "GeistMono Nerd Font", style = "Regular" }
bold   = { family = "GeistMono Nerd Font", style = "Regular" }
italic = { family = "GeistMono Nerd Font", style = "Italic" }
